/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/hello": {
    get: operations["AppController_getData"];
  };
  "/api/config": {
    get: operations["ConfigController_getConfig"];
  };
  "/api/config/init": {
    post: operations["ConfigController_initConfig"];
  };
  "/api/config/update-bot": {
    post: operations["ConfigController_updateBot"];
  };
  "/api/config/add-bot": {
    post: operations["ConfigController_addBot"];
  };
}

export interface components {
  schemas: {
    BotConfigDto: {
      token: string;
      name: string;
      id: number;
    };
    ServerConfigDto: {
      name: string;
      id: number;
      bots: components["schemas"]["BotConfigDto"][];
    };
    CreateBotConfigDto: {
      token: string;
      name: string;
    };
    InitConfigDto: {
      name: string;
      bots: components["schemas"]["CreateBotConfigDto"][];
    };
    UpdateBotConfigDto: {
      token?: string;
      name?: string;
      id: number;
    };
  };
}

export interface operations {
  AppController_getData: {
    parameters: {};
    responses: {
      200: unknown;
    };
  };
  ConfigController_getConfig: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ServerConfigDto"];
        };
      };
      404: unknown;
    };
  };
  ConfigController_initConfig: {
    parameters: {};
    responses: {
      201: unknown;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InitConfigDto"];
      };
    };
  };
  ConfigController_updateBot: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["BotConfigDto"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBotConfigDto"];
      };
    };
  };
  ConfigController_addBot: {
    parameters: {};
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["BotConfigDto"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBotConfigDto"];
      };
    };
  };
}

export interface external {}
